version: '2'

tasks:
  build:
    desc: Builds the API and generates a binary for the current OS
    cmds:
      - go build -mod=vendor .

  run:
    desc: Builds and runs the server locally
    deps: [build]
    sources: 
      - ./*.go
    cmds:
      - ./simple-auth

  vendor:
    desc: Updates the vendor directory
    cmds:
      - go mod tidy
      - go mod vendor

  test:
    desc: Runs go test
    cmds:
      - go test -mod=vendor -v ./api

  cover:
    desc: Runs coverage and generates the needed artifacts
    cmds:
      - go test -mod=vendor -v -coverprofile=coverage.out ./api && gocover-cobertura < coverage.out > coverage.xml && go tool cover -html=coverage.out -o coverage.html

  docker-build:
    desc: Builds and tags the docker image
    cmds:
      - docker build -t "kevineaton/simple-auth:latest" .
  
  docker-slim:
    desc: Builds a slim image.
    deps: [docker-build]
    cmds:
      - docker build -f Dockerfile-slim -t "kevineaton/simple-auth:latest" .

  docker-run:
    desc: Runs the latest built docker image
    deps: [docker-slim]
    cmds:
      - docker run "kevineaton/simple-auth:latest"

  docker-push:
    desc: Builds and tags the docker image then pushes it to the hub
    deps: [docker-slim]
    cmds:
      - docker push "kevineaton/simple-auth:latest"